version: '2.3'
services:
  app:
    build: .
    command: >
      bash -c ' \
        python3 -V \
        && which python3 \
        && python3 -c "import sys; sys.path.append(\"/usr/local/python\"); from openpose import pyopenpose; print(\"Openpose Python Version:\", pyopenpose.__version__)" \
        && python3 01_body_from_image.py
      '
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY # FOR example script
    volumes:
      - ./app:/code
      - /tmp/.X11-unix:/tmp/.X11-unix # FOR example script
